# frozen_string_literal: true

require "fileutils"

namespace :ci do
  desc "Run full CI pipeline locally (mirrors .github/workflows/ci.yml)"
  task all: %i[security lint js assets fasterer python development test db_doctor coverage system audit jev supercov jev_review docker rehearsal] do
    puts "\n✅ All CI checks passed."
  end

  desc "Python wiki-parser tests"
  task :python do
    puts "── Python ──"
    run "#{python_bin} -m unittest lib/wiki_parser/test_parse_itembatches.py"
  end

  desc "Brakeman static security analysis + bundler-audit"
  task :security do
    puts "── Security ──"
    run "bundle exec brakeman --no-pager --exit-on-warn"
    run "bundle exec bundler-audit"
  end

  desc "RuboCop + erb_lint linting"
  task :lint do
    puts "── Lint ──"
    run "bundle exec rubocop"
    run "bundle exec erb_lint app/views"
  end

  desc "active_record_doctor schema-integrity checks"
  task :db_doctor do
    puts "── Schema ──"
    # Reads the test database (built from db/schema.rb) and exits non-zero on a
    # finding. The two detectors that do not fit this schema are turned off in
    # .active_record_doctor.rb, with the reason, so the gate stays a signal.
    run "RAILS_ENV=test bundle exec rake active_record_doctor", clean_env: true
  end

  desc "ESLint + Prettier for the Stimulus controllers"
  task :js do
    puts "── JS ──"
    # The JavaScript side had no linter; these two devDependencies are pinned
    # in package-lock.json, so run the local binaries rather than npx (which
    # would silently fetch a different version).
    unless File.executable?("node_modules/.bin/eslint")
      abort "❌ node_modules is missing — run `npm install` (JS lint uses the pinned devDependencies)"
    end

    run "node_modules/.bin/eslint app/javascript"
    run "node_modules/.bin/prettier --check 'app/javascript/**/*.js'"
  end

  desc "Verify the committed Tailwind bundle is current"
  task :assets do
    puts "── Assets ──"
    # The built bundle is committed. A view that uses a utility which is not in
    # it ships unstyled markup that no test would catch, so rebuild and fail if
    # the committed file was stale.
    bundle = Rails.root.join("app/assets/builds/tailwind.css")
    before = bundle.read
    run "bundle exec rails tailwindcss:build"
    abort "❌ app/assets/builds/tailwind.css is stale — rebuild and commit it" if bundle.read != before
  end

  desc "Fasterer performance-idiom check"
  task :fasterer do
    puts "── Fasterer ──"
    # Suppress RubyParser V40 noise on Ruby 4.0; fasterer falls back to V34
    run "RUBYOPT='-W0' bundle exec fasterer 2>/dev/null || bundle exec fasterer"
  end

  desc "Boot app in development and verify routes"
  task :development do
    puts "── Development ──"
    run "RAILS_ENV=development bundle exec rails db:prepare"
    run "RAILS_ENV=development bundle exec rails runner \"puts 'Rails booted OK: ' + Rails.env\""
    run "RAILS_ENV=development bundle exec rails routes >/dev/null"
    verify_perf_tooling("development")
    run "RAILS_ENV=development bundle exec rake ci:bullet ci:goldiloader"
  end

  desc "Run test suite"
  task :test do
    puts "── Test ──"
    verify_perf_tooling("test", clean_env: true)
    run "RAILS_ENV=test bundle exec rake ci:bullet ci:goldiloader", clean_env: true
    run "RAILS_ENV=test bundle exec rails test", clean_env: true
  end

  desc "Run tests with 89% line / 95% branch coverage enforcement"
  task :coverage do
    puts "── Coverage ──"
    run "RAILS_ENV=test COVERAGE=true bundle exec rails test", clean_env: true
    score = coverage_percent
    puts "Line coverage: #{score}%"
    abort "❌ Coverage is #{score}% — requires 89%" if score < 89

    # Line coverage was 100% while 36 branches (the nil, blank and empty-data
    # sides of guards) were never exercised — branch coverage is what actually
    # holds those paths. 231 of 239 are covered. The eight that are not:
    #   - the `unless Rails.env.development?` on the catch-all rescue_from,
    #     which only takes its other side in development, and
    #   - seven defensive branches in Importers::Datastore (a malformed
    #     ballistics row, a reward kind that is not a hash, a slot with no
    #     allowed items, an empty reward bucket). The importer's own test
    #     covers the canonical shapes; these guard against a source file that
    #     is wrong in a way the committed data never is.
    branches = branch_coverage_percent
    puts "Branch coverage: #{branches}%"
    abort "❌ Branch coverage is #{branches}% — requires 95%" if branches < 95
  end

  desc "Browser (system) tests"
  task :system do
    puts "── System ──"
    run "RAILS_ENV=test bundle exec rails test:system", clean_env: true
  end

  desc "Rubycritic score (≥ 75 threshold)"
  task :audit do
    puts "── Audit ──"
    # Hand-written code only. db/schema.rb is generated by the schema dumper
    # and db/migrate/* are historical snapshots that must not be edited, so
    # auditing them would score files no one should change.
    run "bundle exec rubycritic --no-browser --format json app config test db/seeds.rb"
    score = rubycritic_score
    puts "Rubycritic score: #{score}"
    abort "❌ Score #{score} is below 75 threshold" if score < 75
  end

  desc "Jev (TypeSafe System One) scorecard gate for changed files"
  task jev: :environment do
    puts "── Jev ──"
    # The key is optional so a fork without the secret skips the check rather
    # than failing it; JEV_REQUIRE=1 turns a missing key into a failure.
    unless Jev.enabled?
      abort "❌ TYPESAFE_API_KEY is not set" if ENV["JEV_REQUIRE"] == "1"

      puts "  skipped: TYPESAFE_API_KEY is not set"
      next
    end

    audit = ENV["JEV_ALL"] == "1" ? Jev::Audit.all : Jev::Audit.changed
    # The scorecard calls a paid API, so JEV_LIMIT caps a full-tree run while
    # iterating on the rubrics.
    limit = ENV["JEV_LIMIT"].to_i
    audit = Jev::Audit.new(files: audit.files.first(limit)) if limit.positive?
    if audit.files.empty?
      puts "  no changed files to judge"
      next
    end

    puts "  judging #{audit.files.length} file(s) with #{Jev::MODEL}"
    audit.run
    puts audit.summary
    puts "  report: #{audit.write}"

    # A judgment that errored is an ungated file, not a clean one. Name it on
    # the console; the report carries the error text.
    audit.failed.each { |result| puts "  ⚠️  not judged: #{result.path} — #{result.error}" }

    # Every judgment failed: the gate is blind, and blindness is not a pass.
    if audit.blind?
      abort "❌ Jev judged 0 of #{audit.files.length} file(s) — " \
            "check TYPESAFE_API_KEY and the API"
    end

    if ENV["JEV_MODE"] == "report"
      puts "  JEV_MODE=report — not gating"
      next
    end

    if audit.pass?
      puts "  ✅ no severe judgments"
    else
      audit.violations.each do |violation|
        puts "  ❌ #{violation[:path]} — #{violation[:dimension]} " \
             "#{format('%.2f', violation[:score])} " \
             "(confidence #{format('%.2f', violation[:confidence])})"
      end
      abort "❌ Jev flagged #{audit.violations.length} severe judgment(s)"
    end
  end

  desc "Supercov quality + coverage (Jev-based; report-only unless SUPERCOV_REQUIRE=1)"
  task supercov: :environment do
    puts "── Supercov ──"
    # Both third-party tools below are opt-in: they need a key, a binary or a
    # checkout, and they are not part of the merge gate unless the matching
    # *_REQUIRE flag is set. CI stays green where they are not installed.
    unless Jev.enabled?
      puts "  skipped: TYPESAFE_API_KEY is not set"
      next
    end
    # supercov ships as a platform gem and is deliberately not in the Gemfile,
    # so it runs with an unbundled environment: inside the bundle its binstub
    # refuses to activate a gem the bundle does not contain.
    unless Bundler.with_unbundled_env { system("supercov --version >/dev/null 2>&1") }
      puts "  skipped: supercov is not installed (gem install supercov)"
      next
    end

    report = Rails.root.join("tmp/jev/supercov.txt")
    FileUtils.mkdir_p(report.dirname)
    command = ENV.fetch("SUPERCOV_COMMAND", "quality patch")
    passed = Bundler.with_unbundled_env do
      system("supercov #{command}", chdir: Rails.root.to_s,
                                    out: report.to_s, err: [ :child, :out ])
    end
    puts report.read.lines.last(20).join
    puts "  report: #{report}"
    next if passed || ENV["SUPERCOV_REQUIRE"] != "1"

    abort "❌ supercov failed: #{command}"
  end

  desc "Jev Review (report-only; JEV_REVIEW_AUTO=1 clones it; JS/TS only)"
  task jev_review: :environment do
    puts "── Jev Review ──"
    unless Jev.enabled?
      puts "  skipped: TYPESAFE_API_KEY is not set"
      next
    end

    dir = Pathname.new(ENV.fetch("JEV_REVIEW_DIR", Rails.root.join("tmp/jev-review").to_s))
    if ENV["JEV_REVIEW_AUTO"] == "1" && !dir.join("package.json").exist?
      puts "  cloning devagrawal09/jev-review into #{dir}"
      unless system("git", "clone", "--depth", "1",
                    "https://github.com/devagrawal09/jev-review", dir.to_s)
        abort "❌ could not clone devagrawal09/jev-review"
      end
      unless system("npm", "install", "--no-audit", "--no-fund", chdir: dir.to_s)
        abort "❌ npm install failed in #{dir}"
      end
    end

    unless dir.join("package.json").exist?
      puts "  skipped: no jev-review checkout at #{dir}"
      puts "  enable: JEV_REVIEW_AUTO=1 (clone into tmp) or JEV_REVIEW_DIR=/path/to/jev-review"
      next
    end

    # Run the CLI directly rather than `npm run`: the package scripts pass
    # `--env-file=.env`, and the key is already in this process's environment.
    # Jev Review screens JavaScript and TypeScript only, so a Rails app scopes
    # it at its JS (app/javascript) rather than the repository root.
    mode = ENV.fetch("JEV_REVIEW_MODE", "changes")
    # Resolve the scope against the project, not the checkout the CLI runs in.
    scope = File.expand_path(ENV.fetch("JEV_REVIEW_SCOPE", Rails.root.to_s), Rails.root.to_s)
    verb = ENV["JEV_REVIEW_SAVE"] == "1" ? "save" : "review"
    entrypoint = dir.join("src/cli/#{verb}-#{mode}.ts")
    report = Rails.root.join("tmp/jev/review-#{mode}.json")
    FileUtils.mkdir_p(report.dirname)
    # Progress goes to stderr and the JSON report to stdout, so only stdout is
    # redirected: merging the two would leave a file that is not valid JSON.
    passed = system("node", entrypoint.to_s, scope, chdir: dir.to_s, out: report.to_s)
    puts "  report: #{report}"
    if passed
      puts "  ✅ review written"
    else
      puts "  ⚠️  jev-review did not finish (report-only; set JEV_REVIEW_REQUIRE=1 to gate)"
      puts "     it reviews JavaScript/TypeScript only — set JEV_REVIEW_SCOPE=app/javascript"
      abort "❌ jev-review failed" if ENV["JEV_REVIEW_REQUIRE"] == "1"
    end
  end

  desc "Build production Docker image (same Dockerfile Render deploys)"
  task :docker do
    puts "── Docker ──"
    run "docker build -t #{image_tag} ."
  end

  desc "Rehearse the Render deploy: migrate, boot Puma, poll /up"
  task :rehearsal do
    puts "── Deploy rehearsal ──"
    # Mirrors render.yaml: migrate as preDeployCommand, then boot with
    # Render's dockerCommand and env, and poll healthCheckPath. Uses its own
    # network and throwaway credentials so it needs nothing from the host.
    port = ENV.fetch("CI_REHEARSAL_PORT", "3001")
    network = "tarkov-db-ci-#{Process.pid}"
    db = "#{network}-db"
    app = "#{network}-app"
    database_url = "postgres://postgres:postgres@#{db}:5432/tarkov_db_prod"
    env = {
      "RAILS_ENV" => "production",
      "DATABASE_URL" => database_url,
      "SECRET_KEY_BASE" => ENV["SECRET_KEY_BASE"] || SecureRandom.hex(64),
      "ADMIN_PASSWORD" => ENV.fetch("ADMIN_PASSWORD", "ci-dummy"),
      "RAILS_LOG_TO_STDOUT" => "1",
      "RAILS_SERVE_STATIC_FILES" => "1",
      "RAILS_LOG_LEVEL" => "info",
      "WEB_CONCURRENCY" => "1",
      "RAILS_MAX_THREADS" => "5"
    }

    begin
      run "docker network create #{network}"
      run "docker run -d --name #{db} --network #{network} " \
          "-e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=tarkov_db_prod postgres:18"
      wait_for "postgres", "docker exec #{db} pg_isready -U postgres"

      run "docker run --rm --network #{network} #{env_args(env)} " \
          "#{image_tag} bundle exec rails db:migrate"

      run "docker run -d --name #{app} --network #{network} -p #{port}:3001 " \
          "#{env_args(env.merge('PORT' => '3001'))} " \
          "#{image_tag} bundle exec puma -C config/puma.rb"
      wait_for "http://localhost:#{port}/up", "curl -sf http://localhost:#{port}/up"

      run "docker logs --tail 20 #{app}"
    ensure
      system("docker rm -f #{app} #{db} >/dev/null 2>&1")
      system("docker network rm #{network} >/dev/null 2>&1")
    end
  end

  desc "Verify Bullet N+1 detection is active and strict"
  task :bullet do
    puts "── Bullet ──"
    # Verify stricter settings are present in development.rb
    dev = File.read("config/environments/development.rb")
    abort "❌ Bullet.raise not set" unless dev.include?("Bullet.raise")
    abort "❌ Bullet.unused_eager_loading_enable not set" unless dev.include?("unused_eager_loading_enable")
    abort "❌ Bullet.bullet_logger not set" unless dev.include?("bullet_logger")
    puts "  ✅ Bullet stricter configured (raise=true, unused_eager=true, file log)"
  end

  desc "Verify Goldiloader auto-preload is active globally"
  task :goldiloader do
    puts "── Goldiloader ──"
    dev = File.read("config/environments/development.rb")
    abort "❌ Goldiloader.enabled not set" unless dev.include?("Goldiloader.enabled")
    puts "  ✅ Goldiloader global auto-preload enabled"
  end

  desc "Run security + lint only (fast checks)"
  task quick: %i[security lint js]

  private

  # The wiki parser needs mwparserfromhell and nothing else. Locally that
  # lives in the project venv (see AGENTS.md); CI has no venv, so PYTHON
  # overrides and python3 is the fallback.
  def python_bin
    return ENV["PYTHON"] if ENV["PYTHON"].present?

    venv = File.expand_path("~/.pyvenv-tarkov/bin/python")
    File.executable?(venv) ? venv : "python3"
  end

  # Image tag shared by ci:docker and ci:rehearsal; CI passes the commit sha.
  def image_tag
    ENV.fetch("CI_IMAGE_TAG", "tarkov-db:ci")
  end

  def env_args(env)
    env.map { |key, value| "-e #{key}=#{value}" }.join(" ")
  end

  def wait_for(what, command, attempts: 24)
    attempts.times do
      return puts("  ✅ #{what} ready") if system("#{command} >/dev/null 2>&1")

      sleep 5
    end
    abort "❌ #{what} did not come up within #{attempts * 5}s"
  end

  def run(command, clean_env: false)
    puts "  $ #{command}"
    if clean_env
      # Drop REMOTE database URLs so a stray Neon URL can't hijack the
      # suite, but keep localhost URLs — CI connects via DATABASE_URL.
      env = ENV.to_h.merge(
        "DATABASE_URL" => local_db_url(ENV["DATABASE_URL"]),
        "DATABASE_URL_POOLED" => local_db_url(ENV["DATABASE_URL_POOLED"]),
        "DATABASE_URL_UNPOOLED" => local_db_url(ENV["DATABASE_URL_UNPOOLED"])
      )
      system(env, command) || abort("❌ Command failed: #{command}")
    else
      system(command) || abort("❌ Command failed: #{command}")
    end
  end

  # Returns the URL only when it points at a local database (same hosts
  # as config/initializers/local_database_guard.rb, plus the compose
  # service name); remote URLs come back nil so they're unset.
  def local_db_url(url)
    return nil if url.nil? || url.empty?

    host = begin
      URI.parse(url).host
    rescue URI::InvalidURIError
      nil
    end
    %w[localhost 127.0.0.1 ::1 db].include?(host) ? url : nil
  end

  # Confirms the dev/test-only performance gems (bullet, goldiloader) are
  # actually active in the given environment, not just installed.
  def verify_perf_tooling(env, clean_env: false)
    check = "Bullet.enable? && Goldiloader.enabled? ? " \
            "(puts 'bullet + goldiloader active') : abort('perf tooling not active')"
    run "RAILS_ENV=#{env} bundle exec rails runner \"#{check}\"", clean_env: clean_env
  end

  def coverage_metric(*path)
    require "json"
    data = JSON.parse(File.read("coverage/coverage.json"))
    data.dig("total", *path, "percent").to_f
  rescue Errno::ENOENT
    abort "❌ coverage/coverage.json not found — run tests first"
  end

  def coverage_percent
    coverage_metric("lines")
  end

  def branch_coverage_percent
    coverage_metric("branches")
  end

  def rubycritic_score
    report = "tmp/rubycritic/report.json"
    require "json"
    data = JSON.parse(File.read(report))
    data.fetch("score", 0).to_f
  rescue Errno::ENOENT
    abort "❌ #{report} not found — rubycritic must run first"
  end
end
