services:
  db:
    image: postgres:17
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: tarkov_db_development
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - .:/rails
      - bundle:/bundle
    environment:
      RAILS_ENV: development
      DATABASE_URL: postgres://postgres:secret@db:5432/tarkov_db_development
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true

volumes:
  pgdata:
  bundle:
